spring:
  application:
    name: contract-service
  datasource:
    url: jdbc:postgresql://localhost:5432/contract
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: contracts
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: contracts

server:
  port: 8080

management:
  endpoints.web.exposure.include: health,info,metrics